-- AlterTable
ALTER TABLE "links" ADD COLUMN     "collect_email" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "collect_name" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "countdown_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "countdown_redirect_url" TEXT,
ADD COLUMN     "countdown_seconds" SMALLINT,
ADD COLUMN     "custom_css" TEXT,
ADD COLUMN     "default_utm_campaign" VARCHAR(255),
ADD COLUMN     "default_utm_content" VARCHAR(255),
ADD COLUMN     "default_utm_medium" VARCHAR(255),
ADD COLUMN     "default_utm_source" VARCHAR(255),
ADD COLUMN     "email_required" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "exit_intent_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "exit_intent_message" VARCHAR(255),
ADD COLUMN     "exit_intent_offer" VARCHAR(255),
ADD COLUMN     "interstitial_bg_color" VARCHAR(20),
ADD COLUMN     "interstitial_bg_image" TEXT,
ADD COLUMN     "interstitial_bg_overlay" SMALLINT,
ADD COLUMN     "interstitial_button_text" VARCHAR(100),
ADD COLUMN     "interstitial_description" TEXT,
ADD COLUMN     "interstitial_headline" VARCHAR(255),
ADD COLUMN     "interstitial_logo" TEXT,
ADD COLUMN     "interstitial_theme" VARCHAR(10),
ADD COLUMN     "name_required" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "phone_label" VARCHAR(50),
ADD COLUMN     "privacy_text" VARCHAR(255),
ADD COLUMN     "privacy_url" TEXT,
ADD COLUMN     "security_badges" VARCHAR(50)[],
ADD COLUMN     "social_proof_count" INTEGER,
ADD COLUMN     "social_proof_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "social_proof_text" VARCHAR(100),
ADD COLUMN     "testimonials" JSONB;
